sudo: required
language: ruby
dist: trusty
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install: gem install bundler -v 1.16.1
before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

script: bundle exec rubocop && bundle exec rake
